# Generated by Django 3.1.4 on 2020-12-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='review',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='review',
            name='product_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='review_rating',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
