name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
  
    - name: Build
      run: dotnet build "Shopich/Shopich.csproj"
    - name: Unit-tests
      run: dotnet test "ShopichTests/ShopichTests.csproj"
    - name: Integration tests
      run: dotnet test "ShopichIntegrationTests/ShopichIntegrationTests.csproj"
    - name: E2E tests
      run: dotnet test "ShopichE2ETests/ShopichE2ETests.csproj"
  
